### ISSUE TITLE
How to restore default event types?

### ISSUE THREAD

**Issue by paulmasri** [lisandroct/EventSystem#3]
I accidentally clicked way over to the right of the event types and deleted some of the 'factory defaults'. How can I get them back? (I tried removing and reinstalling the package but it didn't change the Project Settings.)

![Screenshot_2020-09-22_at_18_51_06](https://user-images.githubusercontent.com/496858/93919205-42774d00-fd05-11ea-948b-30e599dc4674.png)

**Comment by paulmasri** [comment]
OK, so I worked out that if I delete the folder `Assets/lisandroct` then the core folders get rebuilt, but I was thinking more of a **Reset defaults** button.

**Comment by lisandroct** [comment]
I just added a button that says "Add Default Events". It's not "Restore Default Events" because so far we have nothing to prevent us from adding duplicates (this is possibly something we want to add in the future), so I'm just adding all the default events as if you were adding them manually, one by one, from the "Add New" tab.
