### ISSUE TITLE
Performance issues when "Add New" in Project Settings

### ISSUE THREAD

**Issue by KufrA** [lisandroct/EventSystem#5]
Using "Unity 2019.4.12f1 LTS"
Very slow GUI reponse when adding new event Types.

As soon as the first letter is filled in either Class or Namespace field Unity Editor lags hard. 1.5sec updates. (Meaning GUI is very slow).
I did some Deep profiling and found that "WhereArrayIterator" is called ones, but roughly 1300000 calls to "TextInfo.ToLower()" is being performed from this single iterator.

I'm not proficient enough with unity to understand really what is going on here. Tried to fiddle with the RegisterSettings.cs script to see if there is an issue i could solve myself.

If you click on four types (so that you reach the max threshold) then everything works fine.

Is this just the way it works?

Picture of the Profiler tree:
![bild](https://user-images.githubusercontent.com/26123598/103956702-5f674d00-5149-11eb-94fc-64180aae1d4a.png)

**Comment by paulmasri** [comment]
Maybe this issue is related to #2

**Comment by lisandroct** [comment]
I'll look into it. I'm sorry, I've been working full time on another project.
The search functionality was always quite slow, it's definitely something we can and should work on.

**Comment by lisandroct** [comment]
I improved performance by reducing the amount of calls to `ToLowerInvariant`. It's still not a very performant search and filter algorithm but it should be fine since this shouldn't be a very frequent operation.
It's worth noting that filtering by type name is significantly faster (will result in less results) than filtering by namespace, so it's advisable to search a type name first and filter by namespace later.
